config/routes.rb
Rails.application.routes.draw do
  root 'welcome#show'

  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :stocks
  resources :user_stocks
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  has_many :user_stocks
  has_many :users, through: :user_stocks

  def self.find_lt_trend(stock_change, spy_change)
    rel_performance = stock_change.to_f - spy_change

    one_yr_sp500_std_dev = 9.16    #source Morningstar, value as of 9/30/15
    limit_overvalued = 2 * one_yr_sp500_std_dev
    limit_somewhat_overvalued = 1 * one_yr_sp500_std_dev
    limit_somewhat_undervalued = -1 * one_yr_sp500_std_dev
    limit_undervalued = -2 * one_yr_sp500_std_dev

    if rel_performance > limit_overvalued
      "Overvalued"
    elsif rel_performance < limit_overvalued && rel_performance > limit_somewhat_overvalued
      "Somewhat overvalued"
    elsif rel_performance < limit_somewhat_overvalued && rel_performance > limit_somewhat_undervalued
      "Fairly valued"
    elsif rel_performance < limit_somewhat_undervalued && rel_performance > limit_undervalued
      "Somewhat undervalued"
    elsif rel_performance < limit_undervalued
      "Undervalued"
    end
  end

  def self.find_st_trend(stock_change, spy_change)
    rel_performance = stock_change.to_f - spy_change.to_f

    daily_sp500_std_dev = 0.98    #source CFA Institute, value as of 8/27/12
    limit_hot = 2 * daily_sp500_std_dev
    limit_outperforming = 1 * daily_sp500_std_dev
    limit_underperforming = -1 * daily_sp500_std_dev
    limit_cold = -2 * daily_sp500_std_dev

    if rel_performance > limit_hot
      "Hot"
    elsif rel_performance < limit_hot && rel_performance > limit_outperforming
      "Outperforming"
    elsif rel_performance < limit_outperforming && rel_performance > limit_underperforming
      "Neutral"
    elsif rel_performance < limit_underperforming && rel_performance > limit_cold
      "Underperforming"
    elsif rel_performance < limit_cold
      "Cold"
    end
  end

  def self.overall_trend(lt_trend, st_trend)
    if (lt_trend == "Overvalued" || lt_trend == "Somewhat overvalued") && (st_trend == "Hot" || st_trend == "Outperforming" || st_trend == "Neutral")
      "Wait to purchase or sell"
    elsif (lt_trend == "Overvalued" || lt_trend == "Somewhat overvalued") && (st_trend == "Underperforming" || st_trend == "Cold")
      "Potential selling opportunity"
    elsif lt_trend == "Fairly valued" && (st_trend == "Hot" || st_trend == "Outperforming")
      "Potential rally in progress"
    elsif lt_trend == "Fairly valued" && (st_trend == "Neutral" || st_trend == "Underperforming")
      "Wait to purchase or sell"
    elsif lt_trend == "Fairly valued" && st_trend == "Cold"
      "Potential drop in progress"
    elsif (lt_trend == "Undervalued" || lt_trend == "Somewhat undervalued") && (st_trend == "Hot" || st_trend == "Outperforming")
      "Potential rebound in progress"
    elsif (lt_trend == "Undervalued" || lt_trend == "Somewhat undervalued") && (st_trend == "Neutral" || st_trend == "Underperforming" || st_trend == "Cold")
      "Wait to purchase or sell"
    end
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :authorize!

  def new
    @stock = Stock.new
  end

  def create
    stock_data = StockQuoteRetrieverService.new.get_quote(stock_params[:ticker])
    if stock_data[:Status] && stock_data[:Status] == "SUCCESS"
      set_new_stock(stock_data)
      flash[:success] = "#{stock_data[:Name]} successfully added!"
      redirect_to stock_path(@stock.id)
    else
      @stock = Stock.new
      flash[:error] = stock_data[:Message]
      render :new
    end
  end

  def index
    @stocks = current_user.stocks
  end

  def show
    @stock = Stock.find_by(id: params[:id])
    @user_stock = UserStock.find_by(user_id: current_user.id, stock_id: @stock.id)
  end

  def update
    @stock = Stock.find_by(id: params[:id])
    stock_data = StockQuoteRetrieverService.new.get_quote(@stock.ticker)
    update_stock(stock_data)

    flash[:success] = "#{stock_data[:Name]} successfully updated!"
    redirect_to stock_path(@stock.id)
  end

  def destroy
    @stock = Stock.find_by(id: params[:id])
    UserStock.find_by(user_id: current_user.id, stock_id: @stock.id).destroy

    flash[:success] = "#{@stock.name} successfully removed!"
    redirect_to stocks_path
  end


  private

  def stock_params
    params.require(:stock).permit(:ticker)
  end

  def set_new_stock(stock_data)
    spy_change = UserStock.find_change_ytd
    lt_trend = Stock.find_lt_trend(stock_data[:ChangePercentYTD], spy_change)
    spy_daily_pct_chg = FinanceScraper.find_spy_daily_percent_change
    st_trend = Stock.find_st_trend(stock_data[:ChangePercent], FinanceScraper.find_spy_daily_percent_change)
    sw_analysis = Stock.overall_trend(lt_trend, st_trend)

    @stock = Stock.create!(
      ticker: stock_data[:Symbol],
      name: stock_data[:Name],
      last_price: stock_data[:LastPrice],
      change: stock_data[:Change],
      change_percent: stock_data[:ChangePercent],
      timestamp: stock_data[:Timestamp],
      market_cap: stock_data[:MarketCap],
      volume: stock_data[:Volume],
      start_value_ytd: stock_data[:ChangeYTD],
      change_ytd: stock_data[:ChangePercentYTD],
      high: stock_data[:High],
      low: stock_data[:Low],
      open: stock_data[:Open],
      spy_chg_ytd: spy_change,
      lt_trend: lt_trend,
      spy_daily_pct_chg: spy_daily_pct_chg,
      st_trend: st_trend,
      recommendation: sw_analysis
    )

    UserStock.create!(stock_id: @stock.id, user_id: current_user.id)
  end

  def update_stock(stock_data)
    spy_change = UserStock.find_change_ytd
    lt_trend = Stock.find_lt_trend(stock_data[:ChangePercentYTD], spy_change)
    spy_daily_pct_chg = FinanceScraper.find_spy_daily_percent_change
    st_trend = Stock.find_st_trend(stock_data[:ChangePercent], FinanceScraper.find_spy_daily_percent_change)
    sw_analysis = Stock.overall_trend(lt_trend, st_trend)

    @stock.update_attributes(
      ticker: stock_data[:Symbol],
      name: stock_data[:Name],
      last_price: stock_data[:LastPrice],
      change: stock_data[:Change],
      change_percent: stock_data[:ChangePercent],
      timestamp: stock_data[:Timestamp],
      market_cap: stock_data[:MarketCap],
      volume: stock_data[:Volume],
      start_value_ytd: stock_data[:ChangeYTD],
      change_ytd: stock_data[:ChangePercentYTD],
      high: stock_data[:High],
      low: stock_data[:Low],
      open: stock_data[:Open],
      spy_chg_ytd: spy_change,
      lt_trend: lt_trend,
      spy_daily_pct_chg: spy_daily_pct_chg,
      st_trend: st_trend,
      recommendation: sw_analysis
    )
  end
end

app/views/stocks/index.html.erb
<head>

  <!-- Bootstrap Core CSS -->
  <link href="css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom CSS -->
  <link href="css/heroic-features.css" rel="stylesheet">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

</head>

<body class="dashboard-body">

  <!-- Navigation -->
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" id="button-logout">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <span class="navbar-brand mega-octicon octicon-flame"></span><a class="navbar-brand" href="/">StockWatcher</a>
          </div>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                  <li id="logout-link">
                      <%= link_to "Logout", logout_path, method: :delete %>
                  </li>
              </ul>
          </div>
      </div>
  </nav>

  <!-- Page Content -->
  <div class="container">
    <h3><span id="welcome-message"><%= image_tag current_user.image_url, class: "img-thumbnail-index" %>&nbsp Welcome, <%=current_user.name %></span></h3>

      <!-- Jumbotron Header -->
      <header class="jumbotron hero-spacer">
        <h1 id="jumbo-text">Welcome to <span id="stockwatcher-title">StockWatcher</span></h1>
        <p>
          StockWatcher lets you add your favorite stocks to your watchlist and track them with ease
        </p>
      </header>

      <div class="stock-button">
        <%= button_to "Add a new stock", new_stock_path, method: :get %>
      </div>&nbsp

      <div class="stock-button">
        <%= button_to "View purchased stocks", user_stocks_path, method: :get %>
      </div>

      <hr>

      <!-- Title -->
      <div class="row">
          <div class="col-lg-12">
              <h2 id="your-watchlist">Your Watchlist</h2>
          </div>
      </div>

      <!-- Page Features -->
      <div class="row text-center">
        <% @stocks.each do |stock| %>
          <div class="col-md-6 col-sm-12 hero-feature">
              <div class="thumbnail" id="profile-rep-box">
                  <div class="caption">
                    <h3 class="key-stats-title"><%= link_to stock.name, stock_path(stock.id) %></h3>
                  </div>
                  <div class="caption", id="box-data">
                    <h4> <span class="name">Name:</span>&nbsp&nbsp<%= stock.name %></h4>
                    <h4> <span class="symbol">Ticker symbol:</span>&nbsp&nbsp<%= stock.ticker %></h4>
                    <h4> <span class="lastprice">Last price:</span>&nbsp&nbsp<%= number_to_currency(stock.last_price) %></h4>
                    <h4> <span class="change">Daily change:</span>&nbsp&nbsp<%= number_to_currency(stock.change) %></h4>
                    <h4> <span class="changepercent">Daily change (%):</span>&nbsp&nbsp<%= number_to_percentage(stock.change_percent, precision: 2) %></h4>
                    <h4 class="trend"> <span class="trendanalysis">StockWatcher Analysis:</span>&nbsp&nbsp<em><%= stock.recommendation %></em></h4>
                  </div>
                  <div class="delete-button">
                    <%= button_to "Remove from watchlist", stock_path(stock.id), method: :delete %>
                  </div>&nbsp
                  <div class="purchase-stock-button">
                    <%= button_to "Add to purchased stocks", edit_user_stock_path(stock.id), method: :get %>
                  </div>
              </div>
          </div>
        <% end %>
      </div>

      <hr>

      <!-- Footer -->
      <footer>
          <div class="container">
              <div class="col-lg-12">
                <div class="copyright-index">
                    <p>Copyright &copy; 2015 StockWatcher, Inc.</p>
                </div>
              </div>
          </div>
      </footer>

  </div>

  <!-- jQuery -->
  <script src="js/jquery.js"></script>

  <!-- Bootstrap Core JavaScript -->
  <script src="js/bootstrap.min.js"></script>

</body>

app/views/stocks/new.html.erb
<head>

  <!-- Bootstrap Core CSS -->
  <link href="css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom CSS -->
  <link href="css/heroic-features.css" rel="stylesheet">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

</head>

<body class="new-body">

  <!-- Navigation -->
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" id="button-logout">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <span class="navbar-brand mega-octicon octicon-flame"></span><a class="navbar-brand" href="/">StockWatcher</a>
          </div>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                  <li>
                      <%= link_to "Logout", logout_path, method: :delete %>
                  </li>
                  <li>
                      <%= link_to "Back to Watchlist", stocks_path %>
                  </li>
              </ul>
          </div>
      </div>
  </nav>

  <div class="container">
    <div id="new-stock-form">
      <br><%= form_for(@stock) do |f| %>
        <%= f.label :ticker, "Ticker symbol:", class: "ticker-label" %>&nbsp
        <%= f.text_field :ticker %><br><br>
        <%= f.submit "Add new stock" %>
      <% end %>
    </div>
  </div>

  <!-- jQuery -->
  <script src="js/jquery.js"></script>

  <!-- Bootstrap Core JavaScript -->
  <script src="js/bootstrap.min.js"></script>
</body>

app/views/stocks/show.html.erb
<head>

  <!-- Bootstrap Core CSS -->
  <link href="css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom CSS -->
  <link href="css/heroic-features.css" rel="stylesheet">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

</head>

<body class="dashboard-body">

  <!-- Navigation -->
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" id="button-logout">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <span class="navbar-brand mega-octicon octicon-flame"></span><a class="navbar-brand" href="/">StockWatcher</a>
          </div>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                  <li>
                      <%= link_to "Logout", logout_path, method: :delete %>
                  </li>
                  <li>
                      <%= link_to "Back to Watchlist", stocks_path %>
                  </li>
              </ul>
          </div>
      </div>
  </nav>

  <!-- Page Content -->
  <div class="container">
      <!-- Title -->
      <div class="row">
          <div class="col-lg-12", id="show-title">
              <h2 id="stock-show-title"><%= @stock.name %></h2>
          </div>
      </div><br>

      <p>
        <strong>Time data last updated: <%= Time.parse(@stock.timestamp).strftime('%A, %d %b %Y %l:%M %p') %></strong>
      </p>

      <div class="update-button">
        <%= button_to "Update data", stock_path(@stock.id), method: :put %>
      </div>

      <br><div class="update-delete-buttons">
        <div class="delete-button">
          <%= button_to "Remove from watchlist", stock_path(@stock.id), method: :delete %>
        </div>&nbsp

        <div class="purchase-stock-button">
          <%= button_to "Add to purchased stocks", edit_user_stock_path(@user_stock.id), method: :get %>
        </div>&nbsp&nbsp&nbsp

        <div class="add-another-stock-button">
          <%= button_to "Add another stock", new_stock_path, method: :get %>
        </div>
      </div>

      <hr>

      <!-- Page Features -->
      <div class="row text-center">
          <div class="col-lg-8 hero-feature" id="price-graph-box">
              <div class="thumbnail graph-placeholder">
                  <div class="caption">
                      <h3 id="key-stats-title">Intra-Day Price History</h3>
                  </div>

                  <div class="price-graph">
                    <%= image_tag "http://chart.finance.yahoo.com/t?s=#{@stock.ticker}&lang=en-US&region=US&width=700&height=420", class: "stock-price-graph" %>
                  </div>
              </div>
          </div>
      </div>

      <div class="row text-center">
          <div class="col-lg-8 hero-feature trading">
              <div class="thumbnail" id="key-trading-statistics">
                  <div class="caption show">
                      <h3 id="key-stats-title">Key Trading Statistics</h3>
                  </div>

                  <div id="show-page-data">
                      <h4> <span class="high"> Daily high: </span> <%= number_to_currency(@stock.high) %></h4>
                      <h4> <span class="low"> Daily low: </span> <%= number_to_currency(@stock.low) %></h4>
                      <h4> <span class="open"> Daily open: </span> <%= number_to_currency(@stock.open) %></h4>
                      <h4> <span class="marketcap"> Market capitalization: </span> $<%= number_to_human(@stock.market_cap, precision: 4) %> </h4>
                      <h4> <span class="volume"> Volume: </span> <%= number_with_delimiter(@stock.volume) %> shares</h4>
                  </div>

              </div>
          </div>
      </div>

      <div class="row text-center">
          <div class="col-lg-8 hero-feature" id="show-box">
              <div class="thumbnail" id="trend-analysis-detail">
                  <div class="caption show">
                      <h3 id="key-stats-title">Trend Analysis Details</h3>
                  </div>
                  <div id="show-page-trend-data">
                      <h4> <span class="trend-detail"> Price at beginning of year: </span> <%= number_to_currency(@stock.start_value_ytd) %></h4>
                      <h4> <span class="trend-detail"> Change year-to-date (%): </span> <%= number_to_percentage(@stock.change_ytd, precision: 2) %></h4>
                      <h4> <span class="trend-detail"> S&P 500 price at beginning of year: </span> $2,058.20 </h4>
                      <h4> <span class="trend-detail"> S&P 500 change year-to-date (%): </span> <%= number_to_percentage(@stock.spy_chg_ytd, precision: 2) %></h4>
                      <h4 class="lt-trend"> <span class="trend-detail"> Long-term trend analysis: </span> <em><%= @stock.lt_trend %></em></h4><br>

                      <h4> <span class="trend-detail"> Daily change (%): </span> <%= number_to_percentage(@stock.change_percent, precision: 2) %></h4>
                      <h4> <span class="trend-detail"> S&P 500 daily change (%): </span> <%= number_to_percentage(@stock.spy_daily_pct_chg, precision: 2) %></h4>
                      <h4 class="lt-trend"> <span class="trend-detail"> Short-term trend analysis: </span> <em><%= @stock.st_trend %></em></h4>
                  </div>
              </div>
          </div>
      </div>


  <!-- jQuery -->
  <script src="js/jquery.js"></script>

  <!-- Bootstrap Core JavaScript -->
  <script src="js/bootstrap.min.js"></script>

</body>