config/routes.rb
Rails.application.routes.draw do
  root 'welcome#show'

  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :stocks
  resources :user_stocks
end

app/models/user_stock.rb
class UserStock < ActiveRecord::Base
  belongs_to :user
  belongs_to :stock

  def total_value(quantity, price)
    quantity.to_i * price.to_f
  end

  def self.find_change_ytd
    original_price = 2058.2
    current_price = FinanceScraper.find_spy_price.delete(',').to_f

    ((current_price - original_price) / original_price) * 100
  end

  def find_stock_return(purchase_price, current_price)
    original_price = purchase_price.delete(',').to_f
    present_price = current_price.delete(',').to_f
    ((present_price - original_price) / original_price) * 100
  end

  def find_spy_return(purchase_price)
    current_price = FinanceScraper.find_spy_price.delete(',').to_f
    original_price = purchase_price.delete(',').to_f

    ((current_price - original_price) / original_price) * 100
  end

  def find_profit_loss(purchase_price, current_price, quantity)
    original_price = purchase_price.delete(',').to_f
    present_price = current_price.delete(',').to_f
    number_of_shares = quantity.delete(',').to_f
    (present_price - original_price) * number_of_shares
  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  before_action :authorize!

  def new
  end

  def create
  end

  def index
    @purchased_user_stocks = UserStock.where(user_id: current_user.id, purchased: true)
  end

  def show
    @user_stock = UserStock.find_by(id: params[:id])
  end

  def edit
    @stock = Stock.find_by(id: params[:id])
    @user_stock = UserStock.find_by(id: params[:id])
  end

  def update
    @user_stock = UserStock.find_by(id: params[:id])
    update_purchase_attributes

    flash[:success] = "Stock purchase successfully created!"
    redirect_to user_stocks_path
  end

  def destroy
  end


  private

  def update_purchase_attributes
    @user_stock.purchase_price = params[:user_stock][:purchase_price]
    @user_stock.quantity = params[:user_stock][:quantity]
    @user_stock.spy_price = FinanceScraper.find_spy_price
    @user_stock.purchased = true

    @user_stock.save!
  end
end

app/views/user_stocks/edit.html.erb
<head>

  <!-- Bootstrap Core CSS -->
  <link href="css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom CSS -->
  <link href="css/heroic-features.css" rel="stylesheet">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

</head>

<body class="new-body">

  <!-- Navigation -->
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" id="button-logout">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <span class="navbar-brand mega-octicon octicon-flame"></span><a class="navbar-brand" href="/">StockWatcher</a>
          </div>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                  <li>
                      <%= link_to "Logout", logout_path, method: :delete %>
                  </li>
                  <li>
                      <%= link_to "Back to Stock", stock_path(@stock.id) %>
                  </li>
                  <li>
                      <%= link_to "Back to Watchlist", stocks_path %>
                  </li>
              </ul>
          </div>
      </div>
  </nav>

  <div class="container">
    <div id="new-stock-form">
      <%= form_for @user_stock do |f| %>
        <%= f.label :purchase_price, "Purchase price:", class: "purchase" %>&nbsp
        <%= f.text_field :purchase_price %><br>

        <%= f.label :quantity, "Num of shares:", class: "purchase" %>&nbsp
        <%= f.text_field :quantity %><br><br>

        <%= f.submit "Submit"%>
      <% end %>
    </div>
  </div>

  <!-- jQuery -->
  <script src="js/jquery.js"></script>

  <!-- Bootstrap Core JavaScript -->
  <script src="js/bootstrap.min.js"></script>
</body>

app/views/user_stocks/index.html.erb
<head>

  <!-- Bootstrap Core CSS -->
  <link href="css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom CSS -->
  <link href="css/heroic-features.css" rel="stylesheet">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

</head>

<body class="dashboard-body">

  <!-- Navigation -->
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" id="button-logout">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <span class="navbar-brand mega-octicon octicon-flame"></span><a class="navbar-brand" href="/">StockWatcher</a>
          </div>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                  <li id="logout-link">
                      <%= link_to "Logout", logout_path, method: :delete %>
                  </li>
                  <li>
                      <%= link_to "Back to Watchlist", stocks_path %>
                  </li>
              </ul>
          </div>
      </div>
  </nav>

  <!-- Page Content -->
  <div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h2 id="your-purchased-stocks">Your Purchased Stocks</h2>
        </div>
    </div>

    <br><% @purchased_user_stocks.each do |user_stock| %>
      <strong><%= link_to user_stock.stock.name, user_stock_path(user_stock.id) %></strong><br>
      Purchase date/time: <%= user_stock.updated_at.strftime('%A, %d %b %Y %l:%M %p') %><br>
      Number of shares: <%= user_stock.quantity %><br>
      Purchase price: <%= number_to_currency(user_stock.purchase_price, precision: 2) %><br>
      <strong>Total value: <%= number_to_currency(
        user_stock.total_value(user_stock.quantity, user_stock.purchase_price),
        precision: 2) %></strong><hr>
    <% end %>
  </div>

  <!-- jQuery -->
  <script src="js/jquery.js"></script>

  <!-- Bootstrap Core JavaScript -->
  <script src="js/bootstrap.min.js"></script>

</body>

app/views/user_stocks/show.html.erb
<head>

  <!-- Bootstrap Core CSS -->
  <link href="css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom CSS -->
  <link href="css/heroic-features.css" rel="stylesheet">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

</head>

<body class="dashboard-body">

  <!-- Navigation -->
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" id="button-logout">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <span class="navbar-brand mega-octicon octicon-flame"></span><a class="navbar-brand" href="/">StockWatcher</a>
          </div>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                  <li id="logout-link">
                      <%= link_to "Logout", logout_path, method: :delete %>
                  </li>
                  <li>
                      <%= link_to "Back to Purchased Stocks", user_stocks_path %>
                  </li>
                  <li>
                      <%= link_to "Back to Watchlist", stocks_path %>
                  </li>
              </ul>
          </div>
      </div>
  </nav>

  <!-- Page Content -->
  <div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h2 id="your-purchased-stocks">Purchase Order: <%= @user_stock.stock.name %></h2>
        </div>
    </div>

    <br><h5><strong>Purchase date/time:</strong> <%= @user_stock.updated_at.strftime('%A, %d %b %Y %l:%M %p') %></h5>
    <h5><strong>Number of shares:</strong> <%= @user_stock.quantity %></h5>
    <h5><strong>Total value:</strong> <%= number_to_currency(
                                @user_stock.total_value(@user_stock.quantity,
                                @user_stock.purchase_price),
                                precision: 2) %></h5><hr>

    <h4><strong>Purchase price:</strong> <%= number_to_currency(@user_stock.purchase_price, precision: 2) %></h4>
    <h4><strong>Return since purchase:</strong> <%= number_to_percentage(@user_stock.find_stock_return(@user_stock.purchase_price, @user_stock.stock.last_price), precision: 2) %></h4><br>

    <h4 class="profit-loss"><strong>Profit/Loss:</strong> <%= number_to_currency(@user_stock.find_profit_loss(@user_stock.purchase_price, @user_stock.stock.last_price, @user_stock.quantity)) %></h4>
  </div>

  <!-- jQuery -->
  <script src="js/jquery.js"></script>

  <!-- Bootstrap Core JavaScript -->
  <script src="js/bootstrap.min.js"></script>

</body>